version: "3.8"

services:
  db:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "VerySecurePassword"
      MYSQL_USER: "Admin_User"
      MYSQL_PASSWORD: "User_Password_Safe"
      MYSQL_DATABASE: "loup_garou"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

  php:
    container_name: symfony_server
    build: .
    restart: "always"
    ports:
      - "80:8000"
    tty: true
    depends_on:
      - db

  mercure:
    container_name: mercure
    image: dunglas/mercure
    restart: unless-stopped
    volumes:
      - ./mercure/Caddyfile:/etc/caddy/Caddyfile
    ports: 
      - "3000:80"
    # environment:
    #   - SERVER_NAME=:80
    #   - MERCURE_PUBLISHER_JWT_KEY=SercuredKey
    #   - MERCURE_SUBSCRIBER_JWT_KEY=SercuredKey
    #   - CORS_ALLOWED_ORIGINS=http://127.0.0.1
    # Uncomment the following line to enable the development mode
    #command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
